#!/bin/sh
set -e

cd "$(git rev-parse --show-toplevel)/backend"

unformatted=$(gofmt -l .)
if [ -n "$unformatted" ]; then
    printf "Go files need formatting (run: cd backend && gofmt -w .):\n%s\n" "$unformatted"
    exit 1
fi
