export const nigeriaStates = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export const nigeriaCitySuggestionsByState = {
  Abia: ["Aba", "Umuahia", "Arochukwu", "Ohafia", "Ugwunagbo"],
  Adamawa: ["Yola", "Jimeta", "Mubi", "Numan", "Ganye"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Oron", "Abak"],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Ekwulobia", "Ogidi"],
  Bauchi: ["Bauchi", "Azare", "Misau", "Jama'are", "Toro"],
  Bayelsa: ["Yenagoa", "Brass", "Ogbia", "Sagbama", "Kaiama"],
  Benue: ["Makurdi", "Gboko", "Otukpo", "Katsina-Ala", "Vandeikya"],
  Borno: ["Maiduguri", "Biu", "Monguno", "Dikwa", "Bama"],
  "Cross River": ["Calabar", "Ikom", "Ogoja", "Ugep", "Obudu"],
  Delta: ["Asaba", "Warri", "Sapele", "Ughelli", "Agbor", "Effurun"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke", "Ishielu", "Ezza"],
  Edo: ["Benin City", "Auchi", "Ekpoma", "Uromi", "Irrua"],
  Ekiti: ["Ado Ekiti", "Ikere", "Oye", "Iyin", "Ise"],
  Enugu: ["Enugu", "Nsukka", "Oji River", "Agbani", "Awgu"],
  FCT: ["Abuja"],
  Gombe: ["Gombe", "Kumo", "Deba", "Billiri", "Bajoga"],
  Imo: ["Owerri", "Orlu", "Okigwe", "Mbaise", "Oguta"],
  Jigawa: ["Dutse", "Hadejia", "Gumel", "Kazaure", "Ringim"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan", "Zonkwa", "Soba"],
  Kano: ["Kano", "Wudil", "Bichi", "Gwarzo", "Rano"],
  Katsina: ["Katsina", "Daura", "Funtua", "Malumfashi", "Mani"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru", "Jega"],
  Kogi: ["Lokoja", "Okene", "Anyigba", "Idah", "Kabba"],
  Kwara: ["Ilorin", "Offa", "Jebba", "Omu-Aran", "Lafiagi"],
  Lagos: ["Lagos", "Ikeja", "Ikorodu", "Epe", "Badagry"],
  Nasarawa: ["Lafia", "Keffi", "Akwanga", "Karu", "Nasarawa"],
  Niger: ["Minna", "Bida", "Suleja", "Kontagora", "Lapai"],
  Ogun: ["Abeokuta", "Ijebu Ode", "Sagamu", "Ota", "Ilaro"],
  Ondo: ["Akure", "Ondo", "Owo", "Ikare", "Ore"],
  Osun: ["Osogbo", "Ile-Ife", "Ilesa", "Ede", "Ikirun"],
  Oyo: ["Ibadan", "Ogbomoso", "Oyo", "Iseyin", "Saki"],
  Plateau: ["Jos", "Bukuru", "Pankshin", "Shendam", "Vom"],
  Rivers: ["Port Harcourt", "Bonny", "Omoku", "Eleme", "Ahoada"],
  Sokoto: ["Sokoto", "Tambuwal", "Wurno", "Gwadabawa", "Illela"],
  Taraba: ["Jalingo", "Wukari", "Bali", "Takum", "Mutum Biyu"],
  Yobe: ["Damaturu", "Potiskum", "Gashua", "Nguru", "Buni Yadi"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka", "Tsafe"],
} as const satisfies Record<(typeof nigeriaStates)[number], readonly string[]>;
