export const PRODUCT_CATEGORY_OPTIONS = [
  "Fashion & Apparel",
  "Shoes",
  "Bags & Accessories",
  "Jewelry & Watches",
  "Beauty & Personal Care",
  "Health & Wellness",
  "Home & Kitchen",
  "Furniture & Decor",
  "Electronics",
  "Phones & Accessories",
  "Baby & Kids",
  "Food & Beverages",
  "Books & Stationery",
  "Arts & Crafts",
  "Sports & Outdoors",
  "Auto Accessories",
  "Other",
] as const;
